
# Page settings

baseURL = "https://cv.birdcolour.com/"
languageCode = "en"
title = "CV - Robin Brown"
theme = "hugo-devresume-theme"

[params]
    author = "CowboySmall"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"
    primaryColor = "#54B689"
    textPrimaryColor = "#292929"
    [params.profile]
        enable = true
        name = "Robin Brown"
        tagline = "Senior Software Engineer"
        avatar = "dp.jpeg"

    [params.contact]
        enable = true
        location = "London"

        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:hello@birdcolour.com"
        text = "hello@birdcolour.com"
#        [[params.contact.list]]
#        icon = "fas fa-globe"
#        url = "https://blog.birdcolour.com"
#        text = "blog.birdcolour.com"

    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "Python"
        [[params.skills.list.items]]
        details = "Redshift/PostgreSQL"
        [[params.skills.list.items]]
        details = "Docker/Kubernetes"
        [[params.skills.list.items]]
        details = "AWS/Private cloud"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Good time management"

    [params.education]
        enable = true

        [[params.education.list]]
        degree = "MPhys Physics with Research Placement; First Class hons"
        university = "University of Sussex"
        dates = "2011 - 2015"
        [[params.education.list]]
        degree = "PhD Neuroimaging; incomplete"
        university = "King's College London"
        dates = "2015 - 2016"


    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"

    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "English"
        level = "Native"
        [[params.languages.list]]
        name = "French"
        level = "Intermediate"

    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Music"
        [[params.interests.list]]
        name = "Swimming"
        [[params.interests.list]]
        name = "Snowboarding"
        [[params.interests.list]]
        name = "Open source software"

    [params.summary]
        enable = true
        text = "Senior software engineer with broad interests in individual contributor roles across data engineering, devops and developer experience, in organisations with a positive, world-improving mission."

    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Software Engineer"
        dates = "2022"
        company = "TrailStone Group"
        details = "Senior engineer supporting teams delivering analytical and transactional Python workloads across the company's renewable energy trading portfolio in the North American marketplace. My primary responsiblities were:"
        [[params.experience.list.items]]
        details = "Creating simple to use, well-tested and dependable developer interfaces to reduce the complexity and fragility of external APIs crucial to trading operations."
        [[params.experience.list.items]]
        details = "Architecting and implementing solutions to enable the continued disassembly of a legacy monolith into more manageable, independently releasable microservices and libraries, increasing developer velocity and system reliability."
        [[params.experience.list.items]]
        details = "Developing novel solutions to long-standing pain points in the development process, leading the expansion of best practices and increasing developer satisfaction."

        [[params.experience.list]]
        title = "Senior Python Developer"
        dates = "2020 - 2022"
        company = "Ricardo Energy & Environment"
        details = "Senior developer in a brand-new and ambitious data science team, supporting a large enterprise of world-leading scientists, engineers, and academics with their most painful data problems, fostering a data science culture within the organisation. My primary responsibilities were:"
        [[params.experience.list.items]]
        details = "Building from the ground up an opensource, Kubernetes-first, GitOps, on-premises, data development stack, setting the standards for other software teams in the organisation (GitLab CI/Minio/Postgres/Vault/Tilt/Argo CD/Microk8s/Ceph)"
        [[params.experience.list.items]]
        details = "Providing leadership and mentoring in the best practices of software design, testing, developer experience, devops, and data strategy"
        [[params.experience.list.items]]
        details = "Managing a wide array of agile projects, products and stakeholders to fixed, contractual deadlines"

        [[params.experience.list]]
        title = "Data Engineer"
        dates = "2017 - 2020"
        company = "YouGov"
        details = "Data engineer operating in a small team focused on developing and maintaining a market-leading dataset and its various data products and services. Developed with a Python/Luigi/Postgres/Redshift/S3 ETL stack, using Docker and in-house deployment tools, supporting a wide range of internal and external data scientists, analysts and other clients. My primary responsibilites were:"
        [[params.experience.list.items]]
        details = "Creating and maintaining a platform to integrate YouGov data into various clients' systems, unifying existing fragmented toolset into a cohesive platform, vastly simplifying maintenance and the end-user experience"
        [[params.experience.list.items]]
        details = "Reducing (by several orders of magnitude) the compute time and memory usage of associated ETL processes, enabling the expansion of this business area into four times as many markets, across twice as many platforms"
        [[params.experience.list.items]]
        details = "Providing third-line support into the data itself, scoping and developing reporting tools, and mentoring colleagues in best use of these"

        [[params.experience.list]]
        title = "Data Engineer"
        dates = "2016"
        company = "SimplifyDigital/Dixons Carphone"
        details = "Data engineer working in an analytics unit, aiming to empower internal and external stakeholders with insights from a deep knowledge of the broadband/TV/landline and mobile phone markets. My primary responsibilities were:"
        [[params.experience.list.items]]
        details = "Making a mobile phone pricing scraper commercially viable by reverse-engineering undocumented APIs and avoiding detection and rate-limiting, slashing the whole-market runtime to hours from days, enabling the expansion of the tool to new retailers and multiple daily updates."
        [[params.experience.list.items]]
        details = "Creating analytics dashboards, and designing and optimising ETL processes to populate them."

    [params.information]
        enable = false

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"


    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/birdcolour"
        title = "birdcolour"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/robin-brown-152309132"
        title = "Robin Brown"




